### ISSUE TITLE
Diff versions: style diffing interface

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/gov_backup#67]
Design elements:
- [ ] bar on the top
- [ ] Information which revisions are being compared (we can add information when this version was last/first seen if it has been seen multiple times)
- [ ] There will be several options to diff two versions (see #59 child tasks) so a chooser might be good
- [ ] Scrolling up/down to next change (nice to have) -> #61 
- [ ] Jumping to a next/prev version
- [ ] For side-by-side comparison (ie. images #63 #56 ) we need a layout that has two sections below the header

In #57 see an attached screenshot of how does diffing interface looks in Versionista.

Example url: http://127.0.0.1:8008/diff/20180401111522..20180518111522/html-formatted/http://www.krs.pl/pl
Draft of a view: https://github.com/epforgpl/gov_backup/blob/master/resources/views/diff.blade.php
